apiVersion: apps/v1
kind: Deployment
metadata:
  name: cibseven-quarkus-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cibseven-quarkus-example
  template:
    metadata:
      labels:
        app: cibseven-quarkus-example
    spec:
      containers:
        - name: quarkus-example
          image: cibseven/cibseven-quarkus-example:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cibseven-quarkus-example
spec:
  selector:
    app: cibseven-quarkus-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
